- hosts: kubernetes
  user: root

  tasks:
    - name: deploy sampleapp on kubernetes cluster
      command: kubectl apply -f myapp-deployment.yml --namespace= "{{ ns }}"

    - name: create service for sampleapp
      command: kubectl apply -f myapp-service.yml --namespace= "{{ ns }}"

    - name: update deployment with new pods if image updated in docker hub
      command: kubectl rollout restart deployment.apps/addressbook --namespace= "{{ ns }}"
